%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% Purpose: Read detected object info (class, bounding box? TL and BR corners) 
%          from dynamically updated text file (generated by graspClasses.py)
% 
% Author:  Jesse Weisberg, 6/13/17
%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
function class = objData(file)

fileID = fopen(file);
C = textscan(fileID, '%s\n');

a = C{1};

class = cell2mat(a(end,:));
% topLeftX = str2double(cell2mat(b(end,:)));
% topLeftY = str2double(cell2mat(c(end,:)));
% bottomRightX = str2double(cell2mat(d(end,:)));
% bottomRightY = str2double(cell2mat(e(end,:)));
% width = bottomRightX - topLeftX;
% height = bottomRightY - topLeftY;

% topLeftX
% topLeftY
% bottomRightX
% bottomRightY
% width
% height

% class of object detected, top left corner coordinates, width, height
% note: these aren't the four corners of the bounding box
% boundingBox =  [topLeftX topLeftY width height];

fclose(fileID);
end
